[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "serialx-desktop"
version = "0.1.0"
description = "Desktop Dashboard for SerialX Arduino communication"
authors = [
    {name = "PredestinatoNew", email = "predestinatonew@gmail.com"},
]
dependencies = [
    "pyserial",
]
requires-python = ">=3.6"

[tool.setuptools]
packages = ["core", "scripts", "ui"]
