name: Release Python Package

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write # Obbligatorio su GitHub per creare le release

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}